### ISSUE TITLE
can you make a example?

### ISSUE THREAD

**Issue by 277850318** [watzak/react-native-instagram-oauth#6]
redirect_url:   YOUR REDIRECT URL  
this is  my redirect_url  igb9e9780e18344d9bbfe0027204ced51d://authorize

![image](https://cloud.githubusercontent.com/assets/8946022/18358956/3e83d0a8-762a-11e6-9ee8-93b0ec2c3c8f.png)

![image](https://cloud.githubusercontent.com/assets/8946022/18376832/f9ee95f2-7694-11e6-86ee-a8d028c218b7.png)

it shows error,how can i fix?

**Comment by watzak** [comment]
Hello

It looks like u have not included a proper redirect_url either in your source code or on instagram itself!

You have to register a new client at manage clients at instagram with a valid redirect url:
Looks something like that:

![screen-shot-2016-09-10-at-11 46 33](https://cloud.githubusercontent.com/assets/8505970/18409652/21f24e00-774d-11e6-9fdb-42010681988d.png)

In your example:
 var instagram: {
     client_id: 'igb9e9780e18344d9bbfe0027204ced51d',
     redirect_url: 'EXAMPLE://main'  
 };

Hope I could help you

Cheers Klausi

**Comment by watzak** [comment]
Hello

I tried following url in the browser with your data and it did not work out =>
https://www.instagram.com/oauth/authorize?response_type=code&client_id=b9e9780e18344d9bbfe0027204ced51d&redirect_uri=igb9e9780e18344d9bbfe0027204ced51d://authorize

Got the same error as u did:
<img width="1097" alt="screen shot 2016-09-10 at 13 25 52" src="https://cloud.githubusercontent.com/assets/8505970/18410149/2d6abd96-775a-11e6-8cf8-9c1d10806e5d.png">

I just tried it with one of my settings and I got following back:
<img width="395" alt="screen shot 2016-09-10 at 13 26 04" src="https://cloud.githubusercontent.com/assets/8505970/18410151/3993ed4a-775a-11e6-825c-e9b46981d5b8.png">

So there must be something wrong with the data! Try to change the redirect url to something simple example://init and try it again!

The redirect URI you use in your app to authenticate has to match with the registered URI.

I think I have found now the issue!
**Do not use Instagram, IG, insta or gram in your app name.**
<img width="763" alt="screen shot 2016-09-10 at 20 38 23" src="https://cloud.githubusercontent.com/assets/8505970/18412740/bd89ea46-7796-11e6-86e9-5dfcc29c1ceb.png">

Then it will probably work for u ;)

Cheers Klausi

**Comment by 277850318** [comment]
it's not help me....

**Comment by sslash** [comment]
I got the exact same error on the Instagram API website (valid redirect URI's must either be HTTP, or HTTPS). What is the correct way to handle link redirection?

**Comment by watzak** [comment]
Hi @sslash 
Instagram has unfortunately changed the validation for redirecturl in their dashboard! So it must be a valid https url!  The one thing to keep in mind is that all requests to the instagram API must be made over SSL (https:// not http://).
The easiest way is to redirect to your own server! So u have to add a valid domain! Within the redirection_url u will also get the access_token!

**Comment by sslash** [comment]
Aha! Makes sense. How would you redirect the client from my server back to the app though (after being redirected from Instagram to my server)?

**Comment by watzak** [comment]
Hi @sslash 

If u have a own server, u can redirect to your mobile app e.g.: myapp:// (keyword: deep linking):

`<!DOCTYPE html>
<html>
    <head>
    <title>iOS Automatic Deep Linking</title>
    </head>
    <body>
        <p>Callback</p>
        <script>
             window.location = "myapp://?"+window.location.hash;
        </script>   
    </body>
</html>`

For further information about deep linking, please check out following sites:
https://medium.com/@ageitgey/everything-you-need-to-know-about-implementing-ios-and-android-mobile-deep-linking-f4348b265b49#.sqbsx29ub
https://medium.com/@pbojinov/deep-links-in-react-native-v0-22-part-1-android-c4b08dbf8eba#.v5i6xnv7e
http://mobiledeeplinking.org/

Hope it helps u ;) 
Can't give u a working example as I am too busy at the moment, but will probably do that in the future ;)

Cheers Klausi

**Comment by machadogj** [comment]
@watzak @sslash I just tried this approach. It works however:
- ~~the redirect should `#` instead of `?`: `window.location = "myapp://#"+window.location.hash;`~~
- the user experience on this is not ideal. It prompts the user to open the app, when in fact it's already opened.

## Cheers!

Edit: actually, the `#` is not required, and neither is the `?`.

**Comment by 277850318** [comment]
this is my code,and successfull.

import React, {Component} from 'react';
import {
    StyleSheet,
    View,
    WebView,
} from 'react-native';

export default class Instagramsdk extends Component {

```
uri='https://api.instagram.com/oauth/authorize/'+
    '?client_id='+INSTAGRAM_CLIENT_ID+
    '&redirect_uri='+HOST+
    '&response_type=token';
webview=null;

onLoadStart(event) {
    var state=event.nativeEvent;
    console.log('onLoadStart',state.url);

    if (/#access_token/.test(state.url) == true) {
        this.webview.stopLoading();
        var accessToken=state.url.split('=').pop();
        var loginExpire=Date.now()+7*24*3600*1000;
        var loginType='instagram';

        //you do.....
    }
}

render() {
    return (
        <View style={styles.container}>
            <WebView
                ref={(webview) => this.webview=webview}
                source={{
                    uri: this.uri,
                }}
                bounces={false}
                domStorageEnabled={true}
                startInLoadingState={true}
                onLoadStart={this.onLoadStart.bind(this)}
            />
        </View>
    );
}
```

}

const styles = StyleSheet.create({
    container:{
        flex:1,
    },
});

**Comment by deitrick** [comment]
@277850318 What did you end up providing in the Instagram dashboard for the redirect_url? Did you go the deep linking route?
